config/routes.rb
TitsProj::Application.routes.draw do

  root :to => 'categories#index'
  mount Resque::Server, :at => '/resque'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :admin do
    get '/events' => 'users#events'
    get '/users/:user_id/navigation/' => 'users#navigation'
    get '/users/:user_id/sign_in/' => 'users#sign_in'
    get '/users/:user_id/sign_out/' => 'users#sign_out'
    get '/users/:user_id/likes/' => 'users#likes'
    get '/users/:user_id/comments/' => 'users#comments'
    get  '/parse' => 'images#parse'
    post '/parse/create_image' => 'images#create_parse_image' #for parsing
    post '/parse' => 'images#parse_images'#for create_img
  end
  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'} do
    get '/auth/:provider/callback' => 'sessions#authf' # For socials networks
    match '/auth/failure' => 'images#index'
  end
  resources :messages, only:[:create]
  resources :images, only: [:index] do
    resource :likes, only:[:create]
    #post '/like' => 'images#like', on: :collection #for likes
    resources :comments, only:[:create]
  end

  resources :categories, only: [:index, :show] do
    resource :subscribes, only: [:create]
    #post '/subscribe' => 'categories#subscribe', on: :collection #for subscribe
    resources :images, only: [:show] do
      resource :comments, only:[:create]
    end
  end
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id             :integer          not null, primary key
#  user_id        :integer          not null
#  eventable_type :string(255)      not null
#  eventable_id   :integer          not null
#  created_at     :datetime         not null
#

class Event < ActiveRecord::Base
  attr_accessible :eventable_id, :eventable_type, :user, :created_at

  belongs_to :user
  belongs_to :eventable, :polymorphic => true

  def self.track_event(type, data = {})
    Resque.enqueue(EventsTracking, type, data)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @search = User.search(params[:q])
    @users= @search.result.order('created_at DESC').page(params[:page]).per(10)
  end

  def navigation
    @events = Event.where(:eventable_type => 'Navigation', :user_id =>params[:user_id]).preload(:eventable).order('created_at DESC').page(params[:page]).per(10)
    @user = User.find(params[:user_id]).nickname
  end

  def sign_in
    @events = Event.where(:eventable_type => 'sign_in', :user_id =>params[:user_id]).order('created_at DESC').page(params[:page]).per(10)
    @user = User.find(params[:user_id]).nickname
  end

  def sign_out
    @events = Event.where(:eventable_type => 'sign_out', :user_id =>params[:user_id]).order('created_at DESC').page(params[:page]).per(10)
    @user = User.find(params[:user_id]).nickname
  end

  def likes
    @events = Event.where(:eventable_type => 'Like', :user_id =>params[:user_id]).order('created_at DESC').page(params[:page]).per(10).includes(:eventable => [:image => :category])
    @user = User.find(params[:user_id]).nickname
  end

  def comments
    @events = Event.where(:eventable_type => 'Comment', :user_id =>params[:user_id]).preload(:eventable).order('created_at DESC').page(params[:page]).per(10).includes(:eventable => [:image => :category])
    @user = User.find(params[:user_id]).nickname
  end
end

app/views/admin/events/comments.html.haml
%table{:id =>'hor-minimalist-b'}
  %thead
    %tr
      %th №
      %th Картинка
      %th Комментарий
      %th Дата
  %tfoot
    %tr
      %td{:colspan => 5}
        =paginate @events
  %tbody
    - @events.each do |e|
      %tr
        %td
          = '33'
        %td
          = link_to "/categories/#{e.eventable.image.category.id}/images/#{e.eventable.image.id}", :id => e.eventable.image.id do
            =image_tag e.eventable.image.url, :height=>50, :width => 50
        %td
          = truncate(e.eventable.body, length: 20, omission: '... (continued)')
        %td
          =e.created_at

app/views/admin/events/index.html.haml
-#= search_form_for @search, url: events_path do |f|
-#  .field
-#    =f.label :nickname_cont, 'Nickname'
-#    =f.text_field :nickname_cont
-#  .actions
-#    =f.submit 'Search'
%table{:id =>'hor-minimalist-b'}
  %thead
    %tr
      %th Пользователь
      %th{:colspan => 5} Действия
  %tfoot
    %tr
      %td{:colspan => 5}
        -#=paginate @users
  %tbody
    - @users.each do |user|
      %tr
        %td
          =user.nickname
        %td
          =link_to 'navigation', "users/#{user.id}/navigation/"
        %td
          =link_to 'sign_in', "users/#{user.id}/sign_in/", :user_id => user.id, :event => 'sign_in'
        %td
          =link_to 'sign_out', "users/#{user.id}/sign_out/", :user_id => user.id, :event => 'sign_out'
        %td
          =link_to 'likes', "users/#{user.id}/likes/", :user_id => user.id, :event => 'likes'
        %td
          =link_to 'comments', "users/#{user.id}/comments/", :user_id => user.id, :event => 'comments'

app/views/admin/events/likes.html.haml
%table{:id =>'hor-minimalist-b'}
  %thead
    %tr
      %th №
      %th Картинка
      %th Дата
  %tfoot
    %tr
      %td{:colspan => 5}
        =paginate @events
  %tbody
    - @events.each do |e|
      %tr
        %td
          = '33'
        %td
          = link_to "/categories/#{e.eventable.image.category.id}/images/#{e.eventable.image.id}", :id => e.eventable.image.id do
            =image_tag e.eventable.image.url, :height=>50, :width => 50
        %td
          =e.created_at

app/views/admin/events/navigation.html.haml
%table{:id =>'hor-minimalist-b'}
  %thead
    %tr
      %th №
      %th Url
      %th Дата
  %tfoot
    %tr
      %td{:colspan => 5}
        =paginate @events
  %tbody
    - @events.each do |e|
      %tr
        %td
          = '33'
        %td
          =e.eventable.url
        %td
          =e.created_at

app/views/admin/events/sign_in.html.haml
%table{:id =>'hor-minimalist-b'}
  %thead
    %tr
      %th №
      %th Дата
  %tfoot
    %tr
      %td{:colspan => 5}
        =paginate @events
  %tbody
    - @events.each do |e|
      %tr
        %td
          = '33'
        %td
          =e.created_at

app/views/admin/events/sign_out.html.haml
%table{:id =>'hor-minimalist-b'}
  %thead
    %tr
      %th №
      %th Дата
  %tfoot
    %tr
      %td{:colspan => 5}
        =paginate @events
  %tbody
    - @events.each do |e|
      %tr
        %td
          = '33'
        %td
          =e.created_at