config/routes.rb
TitsProj::Application.routes.draw do

  root :to => 'categories#index'
  mount Resque::Server, :at => '/resque'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :admin do
    get '/events' => 'users#events'
    get '/users/:user_id/navigation/' => 'users#navigation'
    get '/users/:user_id/sign_in/' => 'users#sign_in'
    get '/users/:user_id/sign_out/' => 'users#sign_out'
    get '/users/:user_id/likes/' => 'users#likes'
    get '/users/:user_id/comments/' => 'users#comments'
    get  '/parse' => 'images#parse'
    post '/parse/create_image' => 'images#create_parse_image' #for parsing
    post '/parse' => 'images#parse_images'#for create_img
  end
  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'} do
    get '/auth/:provider/callback' => 'sessions#authf' # For socials networks
    match '/auth/failure' => 'images#index'
  end
  resources :messages, only:[:create]
  resources :images, only: [:index] do
    resource :likes, only:[:create]
    #post '/like' => 'images#like', on: :collection #for likes
    resources :comments, only:[:create]
  end

  resources :categories, only: [:index, :show] do
    resource :subscribes, only: [:create]
    #post '/subscribe' => 'categories#subscribe', on: :collection #for subscribe
    resources :images, only: [:show] do
      resource :comments, only:[:create]
    end
  end
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id           :integer          not null, primary key
#  name         :string(255)      not null
#  images_count :integer          default(0), not null
#  created_at   :datetime         not null
#

class Category < ActiveRecord::Base
  attr_accessible :name

  has_many :images, :dependent => :destroy
  has_many :subscribes, :dependent => :destroy
  has_many :users, :through => :subscribes

  validates :name, :presence => true, :uniqueness => true

  scope :category_sort_by_images_count, :order =>'images_count DESC'

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]


  def index
    session[:return_to] = request.fullpath
    #@categories = Category.category_sort_by_images_count.includes(:images => [:category]).page(params[:page]).per(5)
    #@images = Image.includes(:category).order('created_at DESC').page(params[:page]).per(5)
    #@likes = Like.last_likes.includes(:user, :image => [:category])
    #@comments = Comment.last_comments.includes(:user, :image=> [:category])
  end

  def show
    session[:return_to] = request.fullpath
    @category = Category.find(params[:id])
    @images = @category.images.includes(:category).order('created_at DESC').page(params[:page]).per(10)
  end

end

app/views/categories/_categories_list.html.haml
#portfolio
  -(@categories = Category.category_sort_by_images_count.includes(:users, :images => [:category]).page(params[:page]).per(5)).each do |cat|
    .item
      =link_to category_path(cat.id) do
        =image_tag cat.images.first.url, :alt => cat.name
      %span
        =cat.name
        (#{cat.images_count})
        -if user_signed_in? && cat.users.include?(current_user)
          =image_tag 'unsubscribe1.jpg', :size => '25x25', :id=>"#{cat.id}", :class=>'subscribe'
        - else
          =image_tag 'subscribe1.jpg', :size => '25x25', :id=>"#{cat.id}", :class=>'subscribe'
.btn-group.paginate
  = paginate @categories, :remote => true, :window => 1

app/views/categories/_categories_list_old.html.haml
%section{:id=>"wrapper"}
  -@categories.each do |cat|
    .imgholder
      %div{:class=>"outer1 circle"}
      %div{:class=>"outer2 circle"}
      %figure
        = link_to category_path(cat.id) do
          = image_tag cat.images.first.url
        %figcaption{:class=>"caption"}
          .text-center
            =cat.name
            %br
            = pluralize(cat.images_count, 'image')
  .clearfix

app/views/categories/_last_comments.html.haml
-Comment.last_comments.includes(:user, :image=> [:category]).each do |com|
  .com_item
    .user
      %strong
        User:
      =com.user.nickname
    .comment
      %strong
        Comment:
      =truncate(com.body, :length => 15, :omission => 'continued')
    .image
      %strong
        Likes:
      =com.image.comments_count
      %strong
        Category:
      =com.image.category.name
      =link_to 'To image', category_image_path(com.image.category.id, com.image.id)

app/views/categories/_last_likes.html.haml
-Like.last_likes.includes(:user, :image => [:category]).each do |like|
  .like_item
    .user
      %strong
        User:
      =like.user.nickname
    .like
      +1 like
    .image
      %strong
        Likes_count:
      =like.image.likes_count
      %strong
        Category:
      =like.image.category.name
      =link_to 'To image', category_image_path(like.image.category.id, like.image.id)

app/views/categories/index.html.haml
.container-fluid
  .row-fluid
    .span12
      #categories_list
        #categories_list-title.text-center
          %h3
            Categories
        #sort
        #categories_content
          -cache("categories_content/#{user_signed_in? ? current_user.cache_key : ''}") do
            =render 'categories/categories_list'
      .row-fluid
        .span6
          -cache('last_likes') do
            #likes_list
              #likes_list-t
                %strong Last 5 likes
              #likes_list-content
                =render 'categories/last_likes'
        .span6
          -cache('last comments') do
            #comments_list
              #comments_list-t
                %strong Last 5 comments
              #comments_list-content
                =render 'categories/last_comments'

app/views/categories/index.js.haml
$('#categories_content').html("#{escape_javascript render partial: 'categories/categories_list'}");
$(".subscribe").click(function() {var id; id = $(this).attr("id"); return $.ajax({ url: "/categories/subscribe", data: { id: id }, dataType: "json", type: "post", success: function(response) { if (response.status === true) { return $("#" + response.id).attr('src', '/assets/unsubscribe1.jpg'); } else { return $("#" + response.id).attr('src', '/assets/subscribe1.jpg'); }}, error: function(xhr, ajaxOptions, thrownError) { return document.location.href = 'http://localhost:3000/users/sign_in'; }  });});

app/views/categories/show.html.haml
.container-fluid
  .row-fluid
    .span12
      #categories_show
        #categories_show-t.text-center
          %h3
            =@category.name.capitalize
        #portfolio
          -@images.each do |img|
            .item
              =link_to "#{@category.id}/images/#{img.id}" do
                =image_tag img.url, :alt => img.url
              %span
                Likes:
                =img.likes_count
                Comments:
                =img.comments_count
        .btn-group.paginate
          = paginate @images, :window => 1
      -##images-list
      -#  #category_title.text-center
      -#    = @category.name
      -#  - @category.images.each do |img|
      -#    #image-item
      -#      =link_to "#{@category.id}/images/#{img.id}" do
      -#        =image_tag img.url, :alt => img.url


    -#.span3
    -#  -cache("categories_content/#{user_signed_in? ? current_user.cache_key : ''}") do
    -#    =render 'categories/categories_menu'
    -#.span9
    -#  #title_images
    -#    = @category.name.capitalize
    -#  #images
    -#    #images-sorted
    -#      -#sorted by
    -#      -#=link_to 'created', root_path
    -#      -#=link_to 'likes', root_path
    -#      -#=link_to 'comments', root_path
    -#    -cache("images_list/#{@category.cache_key}") do
    -#      #images-list
    -#        = render 'images/images_list'
    -#      .btn-group.paginate
    -#        = paginate @images, :remote => true, :window => 1

app/views/categories/show.js.haml
$('#images-list').html("#{escape_javascript render partial: 'images/images_list'}");
$('.btn-group.paginate').html("<div class='text-center'>#{escape_javascript (paginate @images, :remote => true, :window => 1).to_s}</div>");