config/routes.rb
TitsProj::Application.routes.draw do

  root :to => 'categories#index'
  mount Resque::Server, :at => '/resque'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  namespace :admin do
    get '/events' => 'users#events'
    get '/users/:user_id/navigation/' => 'users#navigation'
    get '/users/:user_id/sign_in/' => 'users#sign_in'
    get '/users/:user_id/sign_out/' => 'users#sign_out'
    get '/users/:user_id/likes/' => 'users#likes'
    get '/users/:user_id/comments/' => 'users#comments'
    get  '/parse' => 'images#parse'
    post '/parse/create_image' => 'images#create_parse_image' #for parsing
    post '/parse' => 'images#parse_images'#for create_img
  end
  devise_for :users, :controllers => {:registrations => 'registrations', :sessions => 'sessions'} do
    get '/auth/:provider/callback' => 'sessions#authf' # For socials networks
    match '/auth/failure' => 'images#index'
  end
  resources :messages, only:[:create]
  resources :images, only: [:index] do
    resource :likes, only:[:create]
    #post '/like' => 'images#like', on: :collection #for likes
    resources :comments, only:[:create]
  end

  resources :categories, only: [:index, :show] do
    resource :subscribes, only: [:create]
    #post '/subscribe' => 'categories#subscribe', on: :collection #for subscribe
    resources :images, only: [:show] do
      resource :comments, only:[:create]
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = t('.gallery')
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    -##chat
    -#  #chat-body
    -#    - @messages.each do |mes|
    -#      .chat-mes
    -#        %strong=mes.user.nickname
    -#        %span=mes.created_at
    -#        %p=mes.body
    -#  #chat-form
    -#    =form_for @message, :remote => true do |f|
    -#      = f.text_area :body
    -#      = f.submit 'Send', :class => 'btn'
    -#  %div{:style=>'clear:both;'}
    -#  %div{:style=>'clear:both;'}
    -#%a{:id=>'trigger', :href=>'#'}Chat
    #header
      #top_panel
        -if !user_signed_in?
          %strong=t('.welcome_g')
          #top_panel-buttons
            = link_to t('.login'), new_user_session_path, :class => 'btn btn-inverse'
            = link_to '/auth/facebook' do
              =image_tag 'LoginWithFacebook.png', :size => '150x40'
            = link_to t('.registration'), new_user_registration_path, :class => 'btn btn-inverse'
        - else
          %strong= t('.welcome')
          = current_user.nickname.capitalize
          #top_panel-buttons
            = link_to t('.sign_out'), destroy_user_session_path, :method => :delete, :class => 'btn btn-inverse'
      #title
        =link_to root_path do
          %h1
            = t('.welcome_to_my_gallery')
        %p
          = t('.we_are_glad_to')
    #page
      #header_cleaner
      = yield
      #footer_cleaner
    #footer
      = t('.powered')
      #footer-right-panel
        = link_to 'Adminka', admin_root_path, :class => 'btn'